spring:
  application:
    name: zuul

  profiles:
    active: dao

# server:
#   port:

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
#  routes:
#    api:
#      path: /api/**
#      url: http://localhost:8080/